apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivial-dev
  namespace: dev
spec:
  project: default
  source:
    repoURL: https://github.com/chizchig/snow.git
    targetRevision: HEAD
    path: overlay/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true