name: Build and Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  argocd:
    name: 'ArgoCD Deployment'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Verify System Architecture'
      run: |
        uname -a
        arch

    - name: 'Install Docker'
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: 'Install Minikube'
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/

    - name: 'Start Minikube'
      run: |
        minikube start --driver=docker

    - name: 'Set up Kuberconfig for Minikube'
      run: |
        mkdir -p $HOME/.kube
        minikube update-context

    - name: 'Verify Kubernetes Context'
      run: |
        kubectl config current-context
        kubectl cluster-info

    - name: 'Create Namespaces'
      run: |
        # Create argocd namespace and verify
        kubectl create namespace argocd || true
        kubectl get namespace argocd
        sleep 5
        
        # Create dev namespace
        kubectl create namespace dev || true
        
        # List all namespaces to verify
        kubectl get namespaces

    - name: 'Install ArgoCD'
      run: |
        # Verify argocd namespace exists
        if kubectl get namespace argocd; then
          echo "Installing ArgoCD in namespace 'argocd'..."
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
          
          # Wait for critical ArgoCD components
          echo "Waiting for ArgoCD components to be ready..."
          sleep 30
          kubectl get pods -n argocd
        else
          echo "ArgoCD namespace not found!"
          exit 1
        fi

    - name: 'Configure ArgoCD'
      run: |
        echo "Configuring ArgoCD service..."
        kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

    - name: 'Check ArgoCD version'
      run: |
        kubectl get deployments -n argocd -o jsonpath='{.items[*].spec.template.spec.containers[*].image}' | tr -s '[[:space:]]' '\n' | sort | uniq

    - name: 'Get ArgoCD admin password'
      run: |
        # Wait for secret to be available
        sleep 30
        ARGO_PWD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d || echo "Password not available yet")
        echo "ArgoCD admin password: $ARGO_PWD"
        echo "ARGO_PWD=$ARGO_PWD" >> $GITHUB_ENV

    - name: 'Verify ArgoCD Installation'
      run: |
        echo "Verifying ArgoCD installation..."
        kubectl get all -n argocd